version: '2.3'

services:
    python:
        build:
            context: .
            dockerfile: docker/preprocess/Dockerfile
            args:
                - UID=${UID}
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
        volumes:
            - .:/usr/src
            - /mnt/D/Data/animefacedataset:/usr/src/data/animefacedataset
            - /mnt/D/Data/danbooru:/usr/src/data/danbooru
            - /mnt/D/Data/illustration2vec:/usr/src/data/illustration2vec
            - /mnt/D/Data/celeba:/usr/src/data/celeba
        working_dir: /usr/src
        tty: true
        shm_size: '8gb'
